### ISSUE TITLE
undefined method `split' for nil:NilClass

### ISSUE THREAD

**Issue by ghost** [logstash-plugins/logstash-input-jmx#22]
Hi everyone.

We're trying to use the plugin at our company. We have various machines running logstash 2.3.4 and 2.4, but on both versions we have a problem at logstash starup that should be related to the jmx plugin:

```
$ tail -f /var/log/logstash/logstash.log
...
{:timestamp=>"2016-09-23T10:17:46.978000+0000", :message=>"undefined method `split' for nil:NilClass", :level=>:error}
{:timestamp=>"2016-09-23T10:17:46.978000+0000", :message=>"/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-jmx-2.0.4/lib/logstash/inputs/jmx.rb:165:in `replace_alias_object'\n/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-jmx-2.0.4/lib/logstash/inputs/jmx.rb:240:in `thread_jmx'\norg/jruby/RubyArray.java:1613:in `each'\n/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-jmx-2.0.4/lib/logstash/inputs/jmx.rb:238:in `thread_jmx'\norg/jruby/RubyArray.java:1613:in `each'\n/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-jmx-2.0.4/lib/logstash/inputs/jmx.rb:233:in `thread_jmx'\n/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-jmx-2.0.4/lib/logstash/inputs/jmx.rb:321:in `run'", :level=>:error}
...
```

Any advice?

Thanks in advance

Bruno
- Version:
  - Logstash: both 2.3.4 and 2.4
  - Plugin: 2.0.4
- Operating System: CentOS 7
- Config File:

```
# cat /etc/logstash/conf.d/local_input_tomcat_jmx.conf 
input {
  jmx {
    path => "/etc/logstash/jmx"
    polling_frequency => 10
    type => "jmx-tomcat"
    nb_thread => 1
    add_field => { "[@metadata][local_log]" => "" }
  }
}
```
- Steps to Reproduce:
1. Install logstash from CentOS repo
2. Install jmx plugin
3. Start logstash

**Comment by dhayha** [comment]
Not sure why this is closed.  I'm seeing this issue in logstash 5.3.0

```
[2017-04-21T09:36:28,364][INFO ][logstash.inputs.jmx      ] Loading configuration files in path {:path=>"/path/to/my/jmxconf"}
[2017-04-21T09:37:11,874][ERROR][logstash.inputs.jmx      ] undefined method `split' for nil:NilClass
[2017-04-21T09:37:11,874][ERROR][logstash.inputs.jmx      ] /usr/local/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-jmx-3.0.1/lib/logstash/inputs/jmx.rb:165:in `replace_alias_object'
/usr/local/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-jmx-3.0.1/lib/logstash/inputs/jmx.rb:166:in `replace_alias_object'
/usr/local/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-jmx-3.0.1/lib/logstash/inputs/jmx.rb:240:in `thread_jmx'
org/jruby/RubyArray.java:1613:in `each'
/usr/local/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-jmx-3.0.1/lib/logstash/inputs/jmx.rb:238:in `thread_jmx'
org/jruby/RubyArray.java:1613:in `each'
/usr/local/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-jmx-3.0.1/lib/logstash/inputs/jmx.rb:233:in `thread_jmx'
/usr/local/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-jmx-3.0.1/lib/logstash/inputs/jmx.rb:321:in `run'
```
